package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ProjectFeature
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<ProjectFeature> {
            feature {
                type = "CloudProfile"
                id = "arm-2"
                param("agentPushPreset", "1540497845915")
                param("cloud-code", "arm")
                param("credentialsType", "msi")
                param("description", "")
                param("enabled", "true")
                param("environment", "AZURE")
                param("name", "Azure Cloud")
                param("profileId", "arm-2")
                param("profileServerUrl", "")
                param("secure:passwords_data", "credentialsJSON:e792586a-6c9a-4bbd-8e31-3f014dfd2535")
                param("subscriptionId", "8b53b792-8973-4a30-a63e-4d0e9ff9e3f5")
                param("terminate-idle-time", "30")
                param("total-work-time", "")
            }
        }
        feature1.apply {
            param("system.cloud.profile_id", "arm-2")
            param("agent_pool_id", "-2")
            param("agentPushPreset", "1540504795346")
        }
        add {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_4"
                param("secure:password", "")
                param("name", "RatioInteractive/ci-example-android")
                param("pattern", """#(\d+)""")
                param("authType", "anonymous")
                param("repository", "https://github.com/RatioInteractive/ci-example-android")
                param("type", "GithubIssues")
                param("secure:accessToken", "")
                param("username", "")
            }
        }
    }
}
