package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_4"
                param("secure:password", "")
                param("name", "RatioInteractive/ci-example-android")
                param("pattern", """#(\d+)""")
                param("authType", "anonymous")
                param("repository", "https://github.com/RatioInteractive/ci-example-android")
                param("type", "GithubIssues")
                param("secure:accessToken", "")
                param("username", "")
            }
        }
    }
}
