version: 2

jobs:
  dependencies:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4096m
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run: chmod +x ./gradlew
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  lint_test:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4096m
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run: chmod +x ./gradlew
      - run: ./gradlew lintRelease
      - store_artifacts:
          path: app/build/reports
          destination: reports

  unit_test:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4096m
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: chmod +x ./gradlew
      - run: ./gradlew unitTest
      - store_test_results:
          path: app/build/test-results

  merge_build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4096m
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleRelease

  release_build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4096m
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleRelease -PbuildNumber=${CIRCLE_BUILD_NUM}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/outputs/mapping/
          destination: mapping

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - lint_test:
          requires:
            - dependencies
      - unit_test:
          requires:
            - dependencies
      - merge_build:
          requires:
            - lint_test
            - unit_test
          filters:
            branches:
              ignore: master
      - release_build:
          requires:
            - lint_test
            - unit_test
          filters:
            branches:
              only: master
